pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
	path("", views.index, name='index'),
	path('contact', views.contact,name='contact'),
	path('bots/', views.unfollow_bot, name='unfollow_bot')
]

website_pro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
]

pages/models.py
from django.db import models

class Page(models.Model):
	title = models.CharField(max_length=100)
	permalink = models.CharField(max_length=50)
	body_text = models.TextField('Page content', blank=True, null=True)
	update_date = models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.title

pages/forms.py
from django import forms


class ContactForm(forms.Form):
	name = forms.CharField(max_length=100, required=True)
	email = forms.EmailField()
	subject = forms.CharField(max_length=50)
	message = forms.CharField(widget=forms.Textarea)

	def __init__(self, *args, **kwargs):
		super(ContactForm, self).__init__(*args, **kwargs)

		for x, y in self.fields.items():
			y.widget.attrs.update({'class': 'input'})

	def get_details(self):
		"""
		Method that returns formatted
		information :return: subject, message
		"""

		clean_data = super().clean()

		name = clean_data.get('name').strip()
		from_email = clean_data.get('email')
		subject = clean_data.get('subject')

		msg = f'{name} with email {from_email} said:'
		msg += f'\n"{subject}"\n\n'
		msg += clean_data.get('message')

		return subject, msg

pages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .utils import get_apikeys, getaccess_token
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm
from .models import Page


def index(request):
    page_list = Page.objects.all()
    urls = ('', " ", "/")
    check = False
    if (query:= request.GET.get("q")):
        page = get_object_or_404(Page, permalink__iexact=query)
        if query in urls:
            check = True
    else:
        page = get_object_or_404(Page, permalink='/')
        check = True
    context = {'page_list': page_list, 'page': page, 'check': check}
    return render(request, 'pages/page.html', context)


def contact(request):
    contact_form = ContactForm()
    submitted = None

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            subject, message = contact_form.get_details()

            send_mail(
                subject=subject,
                message=message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[
                    settings.EMAIL_HOST_USER,
                    'olaisaiah54@gmail.com',
                    'isaiaholaoye91@gmail.com'
                ],
                fail_silently=False,
            )
            return redirect('/contact?submitted=True')
        else:
            contact_form = ContactForm()
    if 'submitted' in request.GET:
        submitted = True

    context = {'form': contact_form, 'submitted': submitted}

    return render(request, 'pages/contact.html', context)


def unfollow_bot(request):
    api, api_key = get_apikeys()
    endpoint = None

    if (get_token := request.GET.get('token')) == 'gettoken':
        endpoint = getaccess_token(request, api, api_key)

    if request.method == 'POST':
        token, total_unfollow = request.POST.get(
            'token_num'), request.POST.get('count')
        
        if token and total_unfollow != 'Unfollow Once?':
            api = getaccess_token(request, api, api_key, token)
            if api:
                return HttpResponse(f'{api.verify_credentials()}')
            return HttpResponse('<h1>Couldn\'n authenticate User, Please try again :)</h1>')
        return HttpResponse('<h1> Opps! fill in the form correctly :( </h1>')

    context = {'endpoint': endpoint}

    return render(request, 'pages/bot.html', context)

pages/templates/pages/bot.html
{% extends 'base.html' %}

{% block title %}untitled{% endblock title %}


{% block sidenav %}
	<li><a href="/">Home</a></li>
{% endblock sidenav %}


{% block content %}
<div class='row m-5'>
    <div class='col'>
        <form action='{% url "pages:unfollow_bot" %}'>
            <input type=submit class="btn btn-primary btn-lg" name='token' value='gettoken'>
        </form> 
        <hr>
        {% if endpoint %}
            <p>
                <strong>Visit this url in another browser:</strong>
                <a href="{{ endpoint }}" target="_blank">{{ endpoint }}</a>
            </p>
        {% endif %}  
    </div>
    <div class='col'>
        <form method="POST" action='{% url "pages:unfollow_bot" %}'>
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" class="form-control" name='token_num' placeholder="submit token">
            </div>
            <select class="form-select mb-3" name='count' aria-label="Default select example">
                <option selected>Unfollow Once?</option>
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="15">15</option>
                <option value="20">20</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            <input type="submit" class="btn btn-primary" value='submit'>
        </form>
    </div>
</div>
{% endblock content %}

pages/templates/pages/contact.html

{% extends 'base.html' %}

{% block title %}Contact Us{% endblock title %}

{% block sidenav %}
	<li><a href="/">Home</a></li>
{% endblock sidenav %}

{% block content %}
	<h2>Contact Us</h2>

	{% if submitted %}
	<div class="alert alert-success" role="alert">
  		<p class='success'>
			Your message was sent successfully, Thanks for contacting Us.
		</p>
	</div>
	{% else %}
		<form method="Post" class='m-3'>
			{% csrf_token %}
		{% for field in form %}
		<div class="mb-3">
		    <label>{{ field.label }}</label>
		    <div >{{ field }}</div>
  		</div>
		{% endfor %}
		<input type="submit" value="Send" class='btn btn-success'>
		</form>
	{% endif %}

{% endblock content %}

pages/templates/pages/page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ page.title }}{% endblock title %}


{% block sidenav %}
	{% for page in page_list %}
	<li>
		<a href="{% url 'pages:index' %}?q={{ page.permalink }}">{{ page.title }}</a>
	</li>
	{% endfor  %}
{% endblock sidenav %}


{% block content %}
	<h2>Welcome to {{ page.title }} Page :)</h2>

	{% if check %}
	<div class="row">
	    <div class="col">
	     	<div class="card" style="width: 15rem;">
		  		<img src="{% static 'img/tweet.jpg' %}" class="card-img-top" alt="...">
			  	<div class="card-body">
			    <h5 class="card-title">Unfollower Bot</h5>
			    <p class="card-text">Using AToMates API system, unfollow users that are not following back.</p>
			    <a href="{% url 'pages:unfollow_bot' %}" class="btn btn-primary">Unfollow</a>
			  	</div>
			</div>
	    </div>
	    
	   <div class="col">
	     	<div class="card" style="width: 15rem;">
		  		<img src="{% static 'img/twitter.png' %}" class="card-img-top" alt="...">
			  	<div class="card-body">
			    <h5 class="card-title">Follower Bot</h5>
			    <p class="card-text">Using AToMates API system, follow users your account is yet to follow</p>
			    <a href="{% url 'pages:unfollow_bot' %}" class="btn btn-primary">Follow</a>
			  	</div>
			</div>
	    </div>
{% comment %} 
	    <div class="col mt-2">
	     	<div class="card" style="width: 15rem;">
		  		<img src="{% static 'img/banner.jpg' %}" class="card-img-top" alt="...">
			  	<div class="card-body">
			    <h5 class="card-title">DataStream Bot</h5>
			    <p class="card-text">Using AToMates API system, get your hometimeline, Usertimeline and Searched data.</p>
			    <a href="#" class="btn btn-primary">DataStream</a>
			  	</div>
			</div>
	    </div>

	    <div class="col mt-2">
	     	<div class="card" style="width: 15rem;">
		  		<img src="{% static 'img/banner.jpg' %}" class="card-img-top" alt="...">
			  	<div class="card-body">
			    <h5 class="card-title">AutoTweet Bot</h5>
			    <p class="card-text">Using AToMates API system, Tweet anytime, anywhere without Twitter App.</p>
			    <a href="#" class="btn btn-primary">AutoTweet</a>
			  	</div>
			</div>
	    </div> {% endcomment %} 
  	</div>
	{% endif %}
	<hr>
	<br>
	<div class="container">
		<p>{{ page.body_text|linebreaksbr }}</p>
	</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} Untitled Document {% endblock title %}</title>

	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<!-- custom CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div id='wrapper'>
	<header id="header">
		<div id="topbanner"><img src="{% static 'img/banner.jpg' %}" width="800" height="500" alt=""></div>
	</header>
	<aside id="leftsidebar">
		<nav id="nav">
			<ul>
				{% block sidenav %}
				{% endblock sidenav %}
				<li><a href="{% url 'pages:contact' %}">Contact Us</a></li>
			</ul>
		</nav>
	</aside>
	<section id="main">
		{% block content %}
		{% endblock content %}
	</section>
	<footer id="footer">Copyright &copy; 2022 AToMates Web Design</footer>
</div>
</body>
</html>